import json

class IntegrationInterface:
    def send_feedback(self, agent_id, feedback):
        """
        Send feedback to the agent using the provided agent ID and feedback data.
        
        Parameters:
            agent_id (str): Identifier for the agent receiving feedback.
            feedback (dict): The feedback generated by the Critic.
        
        Returns:
            None
        """
        print(f"Feedback for agent {agent_id}: {json.dumps(feedback, indent=4)}")

    def receive_plan_from_agent(self, agent_id):
        """
        Simulate receiving a city plan from an agent.
        
        Parameters:
            agent_id (str): Identifier for the agent sending the plan.
        
        Returns:
            dict: A sample city plan for testing purposes.
        """
        # Simulated city plan structure (example)
        plan_data = {
            'name': 'Example City',
            'zones': [
                {'type': 'residential', 'area': 1000, 'accessibility': 0.8},
                {'type': 'commercial', 'area': 500, 'accessibility': 0.9},
                {'type': 'industrial', 'area': 300, 'accessibility': 0.7}
            ],
            'infrastructure': {'roads': 'good', 'public_transport': 'adequate'},
            'budget': {'allocated': 1000000, 'actual': 800000}
        }
        print(f"City plan received from agent {agent_id}.")
        return plan_data
